### ISSUE TITLE
alternate class for hiddenInfo

### ISSUE THREAD

**Issue by benaveryee** [hmrc/url-builder#5]
hiddenInfo uses a hard-coded class, 'hidden', to put additional content in the link text. In assets-frontend, this class hides text from both browsers and screen readers. But there is also a 'visuallyhidden' class, which allows screen readers to read the text. This is a common use case, for example to warn that links will open in a new browser tab (which might be shown by an external link icon, not shown in screen readers).
so an optional parameter to hiddenInfo, of the class name, would solve this, and mean we could use url-builder for these links in YTA.

**Comment by howyp** [comment]
@diksta @anthonymunene I think the use case we had for `hiddenInfo` was for screen readers?

**Comment by howyp** [comment]
In any event, I think passing class names around in the code is probably not a great abstraction.

**Comment by nfma** [comment]
@howyp it was and the NVDA screen reader actually read it, though voice over from MacOS didn't. We will give this a go and see if both readers actually read it. We were told that Voice Over has a bug regarding this scenario, so we were happy with the solution we found.

**Comment by benaveryee** [comment]
I think visuallyhidden  is the class we want, rather than hidden. from assets-frontend, govuk-elements/public/sass/elements/_helpers.scss:

``` css
/* Hide for both screenreaders and browsers */
.hidden {
  display: none;
  visibility: hidden; }

/* Hide only visually, but have it available for screenreaders */
.visuallyhidden {
  position: absolute;
  left: -9999em;
}
```
